### PR TITLE
FUSETOOLS2-565 - stabilize UI tests

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
can still flakily fail with:

```
  1) XML DSL support
       Diagnostics for Camel URIs
         "before all" hook for "LSP diagnostics support for XML DSL":
     TimeoutError: Waiting until element is visible
Wait timed out after 5000ms
      at /home/travis/build/camel-tooling/camel-lsp-client-vscode/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at /home/travis/build/camel-tooling/camel-lsp-client-vscode/node_modules/selenium-webdriver/lib/promise.js:2927:27
      at /home/travis/build/camel-tooling/camel-lsp-client-vscode/node_modules/selenium-webdriver/lib/promise.js:668:7
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  From: Task: Waiting until element is visible
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at Driver.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at InputBox.<anonymous> (node_modules/monaco-page-objects/out/components/AbstractElement.js:50:36)
      at Generator.next (<anonymous>)
      at /home/travis/build/camel-tooling/camel-lsp-client-vscode/node_modules/monaco-page-objects/out/components/AbstractElement.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/monaco-page-objects/out/components/AbstractElement.js:4:12)
      at InputBox.wait (node_modules/monaco-page-objects/out/components/AbstractElement.js:49:16)
      at Function.<anonymous> (node_modules/monaco-page-objects/out/components/workbench/input/InputBox.js:29:35)
```

**Comment by apupier** [comment]
> can still flakily fail with:

fixed by checking for enablement and displaying

**Comment by apupier** [comment]
CircleCI is red as the it is not yet configured

**Review by lhein — APPROVED** [review]

**Comment by djelinek** [comment]
Thank you very much @apupier for took over initiative and provide solution how to for now run this failing flaky UI test.

**Pull request merged**
