### PR TITLE
added gchat notifications

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request informations

## Rebase & Merge default requirements

1. Green build for master branch
2. Wait 24 hours after PR creation
3. Green job for PR
4. Approved PR

## PR labels default process

- READY_FOR_REVIEW  &rightarrow;  REVIEW_DONE  &rightarrow;  READY_FOR_MERGE

## Tests

- [ ] Are there **Unit tests**?
- [ ] Are there **Integration tests**?
- [ ] Do we need a new **UI test**?

## PR workflow progress

1. [ ] Tagged with relevant **PR labels**
2. [ ] Green **job for PR**
3. [ ] PR was created more than **24 hours ago** or **All committers approved** it
4. [ ] Green **master** branch build

### CODE REVIEW

**Comment by lhein** [comment]
This will post a gchat notification to our ci room if the build fails on github action.

**Review by bfitzpat — APPROVED** [review]

**Comment by apupier** [comment]
it will create a new thread each time? or post in a dedicated thread? or pick the last thread?

**Comment by apupier** [comment]
is it postign also for Pull requests? or only for master? (i woudl rpefer only for master to avoid too many messages)

**Comment by lhein** [comment]
I don't know if it creates new threads every time. I just tested it once but I also don't see any setting to influence that behavior so we can't do anything about that. Atm it is run for every build by github actions. There might be possiubilities to restrict the execution to a specific branch.

**Comment by lhein** [comment]
Remember, it will only post FAILURE messages for now.

**Review by apupier — CHANGES_REQUESTED** [review]
given that it is redundant with existing mail notifications, I think it shoudl not post message for PR builds to avoid spamming everybody although the PR migth not be ready.

**Review by apupier — COMMENTED** [review]
removing the request to change.
I see no additionnal value personally compared to curren temail notification system used and it is adding a little more code to maintain but won't block merge of it if other developers are finding values for it and maintain it.

**Pull request closed without merging**
