### PR TITLE
FUSETOOLS2-497 - upgrade to vscode-extension-tester 3.0.2

### PR DESCRIPTION
**Pull request by apupier**
update version and fix API break

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request informations

## Rebase & Merge default requirements

1. Green build for master branch
2. Wait 24 hours after PR creation
3. Green job for PR
4. Approved PR

## PR labels default process

- READY_FOR_REVIEW  &rightarrow;  REVIEW_DONE  &rightarrow;  READY_FOR_MERGE

## Tests

- [ ] Are there **Unit tests**?
- [ ] Are there **Integration tests**?
- [ ] Do we need a new **UI test**?

## PR workflow progress

1. [ ] Tagged with relevant **PR labels**
2. [ ] Green **job for PR**
3. [ ] PR was created more than **24 hours ago** or **All committers approved** it
4. [ ] Green **master** branch build

### CODE REVIEW

**Comment by apupier** [comment]
there is now a differetn kind of error:

```
1) XML DSL support
       Camel URI code completion
         Code completion is working for component schemes (the part before the ":"):
     TypeError: Invalid locator
      at Object.check [as checkedLocator] (node_modules/selenium-webdriver/lib/by.js:275:9)
      at EditorView.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2048:18)
      at new AbstractElement (node_modules/monaco-page-objects/out/components/AbstractElement.js:38:48)
      at new ElementWithContexMenu (node_modules/monaco-page-objects/out/components/ElementWithContextMenu.js:18:1)
      at new Editor (node_modules/monaco-page-objects/out/components/editor/Editor.js:19:9)
      at new TextEditor (node_modules/monaco-page-objects/out/components/editor/TextEditor.js:21:1)
      at Context.<anonymous> (out/src/ui-test/xml_completion_support_test.js:49:32)
      at Generator.next (<anonymous>)
      at /home/travis/build/camel-tooling/camel-lsp-client-vscode/out/src/ui-test/xml_completion_support_test.js:8:71
      at new Promise (<anonymous>)
```

**Comment by apupier** [comment]
@djelinek does it ring a bell to you?

**Comment by djelinek** [comment]
I will have to investigate where could be problem. Let me check.

**Comment by mlorinc** [comment]
Hello,

Last error is caused by change introduced in [commit 9172204ec392c2e26efd0987c8a4718d87d41fe0](https://github.com/redhat-developer/vscode-extension-tester/commit/9172204ec392c2e26efd0987c8a4718d87d41fe0#) where `title` argument was removed from `Editor.ts` constructor.

### Fix
Remove title from constructor, so it is not used as locator. Example: [https://github.com/mlorinc/camel-lsp-client-vscode/commit/bb826639ebafee77511cf6c4f8b232ac9e1084d3](https://github.com/mlorinc/camel-lsp-client-vscode/commit/bb826639ebafee77511cf6c4f8b232ac9e1084d3). I have removed `new EditorView()` as well, because editor view is created by default in constructor.

**Comment by apupier** [comment]
@mlorinc thank you! I cherry-picked your commit. Do not hesitate to provide PR on the branch of the PR when you have fix proposal. It is often easier to read the incoming change, and potentially easier to integrate.

**Comment by djelinek** [comment]
Great! Thank you @mlorinc and @apupier for handling it :-)

**Pull request merged**
