### PR TITLE
FUSETOOLS2-921: Launch tests on windows for VS Code language support

### PR DESCRIPTION
**Pull request by djelinek**
Signed-off-by: djelinek <djelinek@eredhat.com>

# Pull Request informations

## Rebase & Merge default requirements

1. Green build for master branch
2. Wait 24 hours after PR creation
3. Green job for PR
4. Approved PR

## PR labels default process

- READY_FOR_REVIEW  &rightarrow;  REVIEW_DONE  &rightarrow;  READY_FOR_MERGE

## Tests

- [ ] Are there **Unit tests**?
- [ ] Are there **Integration tests**?
- [ ] Do we need a new **UI test**?

## PR workflow progress

1. [ ] Tagged with relevant **PR labels**
2. [ ] Green **job for PR**
3. [ ] PR was created more than **24 hours ago** or **All committers approved** it
4. [ ] Green **master** branch build

### CODE REVIEW

**Review by apupier — COMMENTED** [review]
Nice that we have a workaround. I will search which dependencies are pulling this old fsevents causing troubles so that it will be definitely fixed for all projects without upgrading fsevents manually

Can you include in the commit message:
- the issue number FUSETOOLS2-921
- mention that fsevents needs to be upgraded fro compilation on Windows.

**Comment by djelinek** [comment]
> * mention that fsevents needs to be upgraded fro compilation on Windows.

maybe split into two commits? 1st with commit message FUSETOOLS2-291... and 2nd with commit message about fsevents?

**Comment by apupier** [comment]
> > * mention that fsevents needs to be upgraded fro compilation on Windows.
> 
> maybe split into two commits? 1st with commit message FUSETOOLS2-291... and 2nd with commit message about fsevents?

that's great too

**Comment by djelinek** [comment]
Done :-)

**Review by apupier — APPROVED** [review]

**Pull request merged**
