### PR TITLE
updated server jar link

### PR DESCRIPTION
**Pull request by lhein**

### CODE REVIEW

**Comment by lhein** [comment]
I can't tell u. Probably some git magic redirecting. In any way the former url did not work in build while the new one seems to do the trick.

**Comment by apupier** [comment]
I'm asking because I fear that it is working maybe only for the latest available one and that when a new version is available there is some kind of archive process for the artefacts. We will need to monitor that.

**Comment by lhein** [comment]
I am pretty sure it works like that. We should really consider only using tags.

**Comment by apupier** [comment]
downloading as Maven artifact seems even safer: https://github.com/camel-tooling/camel-lsp-client-vscode/issues/7

**Pull request merged**
