### PR TITLE
#19 - Activate Sonar analysis

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by lhein** [comment]
What kind of value do u see in having Sonar active for this project?

**Comment by apupier** [comment]
> What kind of value do u see in having Sonar active for this project?

the same than all other projects.
With an increased value compared to other ones due to:
- we don't know Typescript and Javascript, so it is even more important to have quality analysis
- we will emphasize that currently there is no test

**Comment by apupier** [comment]
current PR state is analyzing only js and not ts (so 1 file out of 3)
Don't know why yet.

**Comment by apupier** [comment]
> current PR state is analyzing only js and not ts (so 1 file out of 3)
> Don't know why yet.

I was trying locally with a too old Sonarqube instance, it is working fine with latest one:
image

**Comment by apupier** [comment]
@lhein what do you think to merge with "rebase and merge" to avoid a linear history and avoid all the "merge pull request " commit as we are doing for Fuse Tooling?

**Comment by lhein** [comment]
damn, my fault.

**Pull request merged**
